# Generated by Django 5.2.4 on 2025-10-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_certification_credential_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Soft Skills', 'Soft Skills'), ('Languages', 'Languages'), ('Tools', 'Tools')], default='Technical', max_length=50)),
                ('level', models.IntegerField(default=3)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_items', to='app.resume')),
            ],
        ),
    ]
