# Generated by Django 5.2.4 on 2025-11-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='extracurricular',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='training',
        ),
    ]
