# """
# Django settings for myresume project.

# Generated by 'django-admin startproject' using Django 5.2.4.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-kphq$nv*j0=b32uyxg55a-817umcf(nazzw(p@^&)(q2nj5xh6'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
    

#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'app',

# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'myresume.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'myresume.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ROOT_URLCONF = 'myresume.urls'


# STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR / 'app/static']
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

# LOGIN_REDIRECT_URL = 'home'
# LOGOUT_REDIRECT_URL = 'login'


#
# Project Structure & Setup Instructions
#
# This code provides the core files for your Django resume builder.
# To use it, follow these steps:
#
# 1. Create a new Django project:
#    django-admin startproject myresume
#    cd myresume
#
# 2. Create the 'app' app:
#    python manage.py startapp app
#
# 3. Create a 'templates' directory inside your 'app' folder.
#    mkdir app/templates
#
# 4. Create a 'templates/auth' and 'templates/resume' directory inside 'app/templates/'.
#    mkdir app/templates/auth
#    mkdir app/templates/resume
#
# 5. Create a 'static' and 'media' directory in your main 'myresume' project folder.
#    mkdir static
#    mkdir media
#
# 6. Install required packages:
#    pip install django djangorestframework django-crispy-forms Pillow xhtml2pdf
#
# 7. Copy and paste the code below into the corresponding files.
#    (Note: You will need to create and populate the empty files mentioned)
#
# 8. Configure Tailwind CSS.
#    (This code assumes you have set up Tailwind and generated the `tailwind.css` file
#    in your `static/css/` directory. You will need to use `npm` to install and build it.)
#
# 9. Run the development server:
#    python manage.py makemigrations
#    python manage.py migrate
#    python manage.py runserver
#
# You will find all the necessary code for a full-stack resume builder below,
# organized by file name for easy copy-pasting.
#

# =========================================================================
# File: myresume/settings.py
# =========================================================================
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-@e5@&d8%89z7t2c2i#qj0y5d-s=6_m=n+m8%a5(8_i5d*v!i+^'

DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myresume.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'app/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myresume.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # Increase the timeout so short concurrent writes wait instead of failing
        'OPTIONS': {
            'timeout': 20,
            'init_command': "PRAGMA journal_mode=WAL;",
        },
    }
}

# Improve SQLite concurrency in development by enabling WAL and setting busy timeout
# This makes transient "database is locked" errors less likely. For production use
# consider PostgreSQL or another server-grade database.
from django.db.backends.signals import connection_created

def _sqlite_connection_created(sender, connection, **kwargs):
    if connection.vendor == 'sqlite':
        try:
            cursor = connection.cursor()
            # Enable WAL journal mode for better concurrency
            cursor.execute('PRAGMA journal_mode=WAL;')
            # Make sure busy timeout is set at the SQLite level too (ms)
            cursor.execute('PRAGMA busy_timeout=20000;')
        except Exception:
            # Non-fatal; if this fails we still continue with default settings
            pass

connection_created.connect(_sqlite_connection_created)

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'app/static')]

# Tell Django where to collect static files
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication URLs
LOGIN_REDIRECT_URL = 'app:resume_list'
LOGOUT_REDIRECT_URL = 'login'

LOGIN_URL = 'login'

CSRF_COOKIE_SECURE = False